name: dnsolve
description: Pure Dart library that provides an easy way to perform DNS lookups using native resolution via FFI
version: 3.0.0
repository: https://github.com/vsevex/dnsolve
issue_tracker: https://github.com/vsevex/dnsolve/issues
topics: [network, dns, ffi]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.5

dev_dependencies:
  lint: ^2.8.0
  test: ^1.29.0

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
