name: dnsolve
description: Pure Dart library that provides an easy way to perform DNS lookups
version: 2.0.0
repository: https://github.com/vsevex/dnsolve
issue_tracker: https://github.com/vsevex/dnsolve/issues
topics: [network, http, dns]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.6.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.29.0

platforms:
  android:
  ios:
  linux:
  web:
  windows:
